### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by ericasberry** [apizzimenti/cli-weather#16]
Installed per instructions, running Mac OSX Yosemite 10.10.5 and node v0.12.2.  

Command: weather -a "Tampa, FL"

result:

/usr/local/lib/node_modules/cli-weather/lib/data.js:30
        if (units.tmp.includes('C')) {
                      ^
TypeError: undefined is not a function
    at /usr/local/lib/node_modules/cli-weather/lib/data.js:30:23
    at Array.forEach (native)
    at Object.collectHighs (/usr/local/lib/node_modules/cli-weather/lib/data.js:26:10)
    at new Format (/usr/local/lib/node_modules/cli-weather/lib/format.js:14:23)
    at instance (/usr/local/lib/node_modules/cli-weather/lib/format.js:28:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cli-weather/lib/args.js:28:31)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by pizzimathy** [comment]
Thank you, I totally forgot `includes()` was ES6 when I added it. Good catch!

**Comment by ericasberry** [comment]
No problem, glad to help.  It's a very handy utilitiy - thanks for writing
it!
