### ISSUE TITLE
SyntaxError: Unexpected token F in JSON at position 0

### ISSUE THREAD

**Issue by windyinsc** [apizzimenti/cli-weather#23]
Not sure if this is a build failure within the program itself or on my end.

``` bash
user @ ~ [1] → weather
powered by Forecast.io
  ##undefined:1
Forbidden
^

SyntaxError: Unexpected token F in JSON at position 0
    at Object.parse (native)
    at new Format (/usr/local/lib/node_modules/cli-weather/lib/format.js:9:20)
    at instance (/usr/local/lib/node_modules/cli-weather/lib/format.js:30:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cli-weather/lib/args.js:27:31)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by pizzimathy** [comment]
I just changed the API key for Forecast.io, so I'll replace the key and republish.

**Comment by pizzimathy** [comment]
Update published with an updated API key. If this issue persists, open a new issue and I'll try to figure out what's going on.

**Comment by windyinsc** [comment]
Works like a charm! Major Kudos for taking such quick action on this.
