### ISSUE TITLE
TypeError: min = Object.assign(min, re)

### ISSUE THREAD

**Issue by nickwales** [apizzimenti/cli-weather#31]
Running with options e.g. `-z` works. Saved those options with `-s` but subsequently running doesn't work with the following error:

```# weather

/opt/boxen/nodenv/versions/v0.10.31/lib/node_modules/cli-weather/lib/weather/Config.js:40
        min = Object.assign(min, re);
                     ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at Object.config_weather (/opt/boxen/nodenv/versions/v0.10.31/lib/node_modules/cli-weather/lib/weather/Config.js:40:22)
    at Object.<anonymous> (/opt/boxen/nodenv/versions/v0.10.31/lib/node_modules/cli-weather/lib/index.js:8:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3```

**Comment by pizzimathy** [comment]
@nickwales I take it that you're running macOS - what versions of node.js and cli-weather are you running? I can't replicate the error with my current version(s), so I can try and debug it with nvm.

**Comment by nickwales** [comment]
Does this help (I'm not particularly well versed with node, just saw your post on reddit and tried it out):

```
$ node -v
v0.10.31
```

```
$ npm v cli-weather
{ name: 'cli-weather',
  description: 'Puts the weather in your console.',
  'dist-tags': { latest: '2.0.3' },
  versions:
   [ '0.0.2',
     '0.0.4',
     '0.0.6',
     '0.1.0',
     '1.0.0',
     '1.1.2',
     '1.2.0',
     '1.2.1',
     '1.2.2',
     '1.2.3',
     '1.2.4',
     '1.2.5',
     '1.2.6',
     '1.2.7',
     '1.2.8',
     '1.3.0',
     '1.3.1',
     '1.3.2',
     '1.3.3',
     '1.3.4',
     '1.3.5',
     '1.3.6',
     '1.3.7',
     '1.3.61',
     '1.3.62',
     '1.3.63',
     '1.3.64',
     '1.3.66',
     '1.3.71',
     '1.3.72',
     '1.3.73',
     '1.3.74',
     '1.3.75',
     '1.3.76',
     '1.3.77',
     '1.3.78',
     '1.3.79',
     '1.3.80',
     '1.3.81',
     '1.3.82',
     '1.3.83',
     '1.3.84',
     '1.3.85',
     '1.3.86',
     '1.3.87',
     '1.4.0',
     '1.4.1',
     '1.4.2',
     '1.5.0',
     '1.5.1',
     '1.5.2',
     '1.5.3',
     '1.5.4',
     '1.5.5',
     '1.5.6',
     '1.5.7',
     '1.5.8',
     '1.5.9',
     '1.5.10',
     '1.5.11',
     '1.5.13',
     '2.0.0',
     '2.0.1',
     '2.0.2',
     '2.0.3' ],
  maintainers: 'apizzimenti <pizzimentianthony@gmail.com>',
  time:
   { modified: '2017-01-02T10:24:34.432Z',
     created: '2015-12-27T20:25:00.274Z',
     '0.0.2': '2015-12-27T20:25:00.274Z',
     '0.0.4': '2015-12-27T20:29:22.286Z',
     '0.0.6': '2015-12-29T00:44:14.000Z',
     '0.1.0': '2015-12-29T07:34:08.900Z',
     '1.0.0': '2015-12-29T07:35:09.733Z',
     '1.1.2': '2015-12-29T20:53:16.404Z',
     '1.2.0': '2015-12-29T23:00:28.898Z',
     '1.2.1': '2015-12-29T23:22:00.907Z',
     '1.2.2': '2015-12-30T01:45:39.152Z',
     '1.2.3': '2015-12-30T02:34:18.200Z',
     '1.2.4': '2015-12-30T02:34:39.850Z',
     '1.2.5': '2015-12-30T02:47:23.080Z',
     '1.2.6': '2015-12-30T04:54:06.656Z',
     '1.2.7': '2016-01-01T00:28:38.856Z',
     '1.2.8': '2016-01-01T05:45:32.340Z',
     '1.3.0': '2016-01-01T07:42:57.724Z',
     '1.3.1': '2016-01-01T15:58:28.826Z',
     '1.3.2': '2016-01-01T16:49:49.615Z',
     '1.3.3': '2016-01-02T21:06:10.547Z',
     '1.3.4': '2016-01-02T21:08:37.655Z',
     '1.3.5': '2016-01-02T21:14:05.777Z',
     '1.3.6': '2016-01-04T01:08:17.490Z',
     '1.3.61': '2016-01-04T01:09:15.082Z',
     '1.3.62': '2016-01-04T01:11:13.128Z',
     '1.3.63': '2016-01-04T01:12:28.650Z',
     '1.3.64': '2016-01-04T01:13:44.743Z',
     '1.3.66': '2016-01-04T15:32:49.834Z',
     '1.3.7': '2016-01-04T15:45:20.200Z',
     '1.3.71': '2016-01-04T15:50:32.769Z',
     '1.3.72': '2016-01-04T19:32:19.024Z',
     '1.3.73': '2016-01-04T20:44:02.877Z',
     '1.3.74': '2016-01-08T19:35:21.363Z',
     '1.3.75': '2016-01-17T07:14:47.984Z',
     '1.3.76': '2016-01-17T07:24:05.955Z',
     '1.3.77': '2016-01-17T18:33:32.139Z',
     '1.3.78': '2016-01-17T18:40:15.936Z',
     '1.3.79': '2016-01-21T18:37:09.682Z',
     '1.3.80': '2016-01-25T19:51:21.202Z',
     '1.3.81': '2016-01-25T19:53:25.853Z',
     '1.3.82': '2016-01-25T21:21:25.641Z',
     '1.3.83': '2016-01-26T01:27:32.844Z',
     '1.3.84': '2016-01-26T19:00:24.914Z',
     '1.3.85': '2016-01-27T21:26:44.313Z',
     '1.3.86': '2016-02-11T19:49:05.412Z',
     '1.3.87': '2016-02-28T21:30:18.917Z',
     '1.4.0': '2016-05-02T14:18:12.855Z',
     '1.4.1': '2016-05-02T14:26:03.312Z',
     '1.4.2': '2016-05-02T14:41:51.838Z',
     '1.5.0': '2016-05-06T23:20:05.889Z',
     '1.5.1': '2016-05-06T23:33:03.079Z',
     '1.5.2': '2016-05-06T23:35:32.511Z',
     '1.5.3': '2016-05-06T23:58:28.226Z',
     '1.5.4': '2016-05-06T23:58:41.894Z',
     '1.5.5': '2016-05-06T23:59:58.781Z',
     '1.5.6': '2016-05-07T00:10:04.635Z',
     '1.5.7': '2016-05-07T03:10:13.274Z',
     '1.5.8': '2016-05-07T03:47:45.201Z',
     '1.5.9': '2016-05-07T03:56:58.838Z',
     '1.5.10': '2016-05-07T05:30:47.166Z',
     '1.5.11': '2016-06-14T15:15:58.645Z',
     '1.5.13': '2016-07-28T16:02:25.770Z',
     '2.0.0': '2017-01-02T10:20:42.526Z',
     '2.0.1': '2017-01-02T10:21:06.937Z',
     '2.0.2': '2017-01-02T10:22:17.660Z',
     '2.0.3': '2017-01-02T10:24:34.432Z' },
  homepage: 'https://github.com/apizzimenti/cli-weather#readme',
  repository:
   { type: 'git',
     url: 'git+https://github.com/apizzimenti/cli-weather.git' },
  author: 'Anthony Pizzimenti',
  bugs: { url: 'https://github.com/apizzimenti/cli-weather/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  users:
   { apizzimenti: true,
     steffes: true,
     xch: true,
     nichoth: true,
     rlihm: true,
     cderleth84: true,
     'john-goldsmith': true },
  keywords:
   [ 'weather',
     'cli',
     'command',
     'line',
     'tool',
     'package',
     'node',
     'location' ],
  version: '2.0.3',
  main: 'index.js',
  scripts:
   { test: 'mocha',
     prebuild: 'rimraf dist/**/* ../cli-weather-docs/**/*',
     postbuild: 'jsdoc -c ~/desktop/cli-weather/jsdoc.json' },
  bin: { weather: './lib/index.js' },
  preferGlobal: true,
  dependencies:
   { chalk: '^1.1.3',
     'cli-table2': '^0.2.0',
     geocoder: '^0.2.2',
     minimist: '^1.2.0',
     'node-emoji': '^1.4.3',
     request: '^2.79.0',
     'update-notifier': '^1.0.3',
     wordwrap: '^1.0.0' },
  devDependencies: { jsdoc: '^3.4.3', mocha: '^3.2.0' },
  gitHead: '0685394fa7f17da56b20965e4278e94c98f7c111',
  dist:
   { shasum: 'd0cfeaf91f628da9c5ae76a4a7b1d828351c31fd',
     tarball: 'https://registry.npmjs.org/cli-weather/-/cli-weather-2.0.3.tgz' },
  directories: {} }
```

**Comment by pizzimathy** [comment]
Yep, that helps a lot! I think updating node would do you a world of good - [v0.10.31 was released on August 19, 2014.](https://nodejs.org/en/blog/release/v0.10.31/)

[`Object.assign(target, source [,sources])`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility) is an Object method that was introduced as part of the ECMAScript 2015 spec. Checking your version against [node.green](http://node.green/#built-in-extensions) shows that v0.10.31 does not support `Object.assign()`, and that's why you're getting the error.

[Here](https://nodejs.org/en/download/) is the download page for the newer versions of node. Both the LTS and Current versions will work with nearly all packages (cli-weather included). In the meantime, I'll try and get backward-compatibility support built into the client itself.

Let me know how it goes and if updating node works out.
