### ISSUE TITLE
Error: Cannot find module '../../../private.json'

### ISSUE THREAD

**Issue by schvabodka-man** [apizzimenti/cli-weather#46]
Hi there. Just installed your app on fedora with npm. Trying to run it and it gives me
`
module.js:471
    throw err;
    ^

Error: Cannot find module '../../../private.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/cli-weather/lib/weather/Data/Weather.js:15:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
`

**Comment by pizzimathy** [comment]
Seems to be a recurring issue with my install, but doesn't come up in my tests. Looking into it.

**Comment by dennisblokland** [comment]
some isue

**Comment by pizzimathy** [comment]
The missing file includes the API key, and I didn't want it to be available through the GitHub distribution, so I `.gitignore`d it. Just added a blank `.npmignore` so it doesn't end up on git, but is still distributable through npm.

Sorry this took so long to fix.
